# Site settings
title:       dnsh.io
email:       dvitharanage@gmail.com
author:      Dinesh Vitharanage
description: "One mans rant is another mans bant."
baseurl:     ""
url:         "http://dnsh.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: "UA-84675614-1"
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id: 

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: dnshio

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: dvitharanage
bitbucket_username:
stackoverflow_id:
twitter_username: killneel
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: dinesh-vitharanage-681a4829
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: flase
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Spread this shit!'
    facebook:     'Spread this on Facebook'
    twitter:      'Spread this on Twittah'
    googleplus:   'Spread this on Google+'
    linkedin:     'Spread this on LinkedIn'
    digg:         'Digg this shit'
    tumblr:       'Spread this on Tumblr'
    reddit:       'Spread this on Reddit'
    stumbleupon:  'Spread this on StumbleUpon'
    hackernews:   'Spread this on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Your email'
    content:  'Spill it'
    subject:  'New submission from the dnsh.io'
    submit:   'Come at me bro!'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: "Safe. I will get back to you if it's important"
  og_locale: 'en_UK'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
