# Site settings
#title: Command.run
#email: dvitharanage@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Collective thoughts from a single perspective through murky lenses of D Vitharanage's eyes
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.command.run" # the base hostname & protocol for your site
#twitter_username: killneel
#github_username:  dvitharanage
#
## Build settings
#markdown: kramdown


title:            Command.run
description:      Collective thoughts from a single perspective through murky lenses of D Vitharanage's eyes
logo:             cmd-run-logo.png
disqus_shortname: commandandrun
# Assign a default image for your site's header and footer
default_bg:       some-image.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              "http://localhost:4000"


# Owner/author information
owner:
  name:           Dinesh Vitharanage
  avatar:         mugshot.jpg
  email:          dvitharanage@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Medium sized free-range thinker
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:
  facebook:
  github:
  linkedin:
  instagram:
  tumblr:
#  hmfaysalsocial:
#  # For Google Authorship https://plus.google.com/authorship
#  google_plus:    "http://plus.google.com/123123123123132123"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Me
    url: /about-me
#  - title: Tags
#    url: /tags
  - title: About this site
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class